export const mockClients = [
  {
    id: 20,
    name: "John Doe",
    type: "Individual",
    email: "johndoe@email.com",
    status: "Active",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
    updatedBy: "hello world",
  },
  {
    id: 21,
    name: "Test Test",
    type: "Individual",
    email: "test@test.com",
    status: "Active",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-18"),
    updatedBy: "hello world",
  },
  {
    id: 15,
    name: "Acme Corporation",
    type: "Company",
    email: "contact@acme.com",
    status: "Active",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-25"),
    updatedBy: "admin user",
  },
  {
    id: 8,
    name: "Jane Smith",
    type: "Individual",
    email: "jane.smith@email.com",
    status: "Pending",
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-22"),
    updatedBy: "system",
  },
  {
    id: 33,
    name: "Tech Solutions Ltd",
    type: "Company",
    email: "info@techsolutions.com",
    status: "Inactive",
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-16"),
    updatedBy: "manager",
  },
  {
    id: 42,
    name: "Alice Johnson",
    type: "Individual",
    email: "alice.j@email.com",
    status: "Active",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-24"),
    updatedBy: "hello world",
  },
  {
    id: 7,
    name: "Global Industries",
    type: "Company",
    email: "hello@global.com",
    status: "Active",
    createdAt: new Date("2024-01-03"),
    updatedAt: new Date("2024-01-28"),
    updatedBy: "admin user",
  },
  {
    id: 55,
    name: "Bob Wilson",
    type: "Individual",
    email: "bob.wilson@email.com",
    status: "Pending",
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-19"),
    updatedBy: "system",
  },
];
